_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 41
                - 49
                - 55
                - 71
            "3":
                - 13
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
